-- Insurance and Compliance Tables Migration

-- Insurance Information Table
CREATE TABLE insurance_info (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    payer_id VARCHAR(50) NOT NULL,
    member_id VARCHAR(100) NOT NULL,
    group_number VARCHAR(100),
    subscriber_first_name VARCHAR(100),
    subscriber_last_name VARCHAR(100),
    subscriber_dob DATETIME,
    relationship_to_patient VARCHAR(50),
    policy_number VARCHAR(100),
    plan_type VARCHAR(50),
    copay_amount DECIMAL(10,2),
    deductible_amount DECIMAL(10,2),
    coinsurance_percentage DECIMAL(5,2),
    is_primary BOOLEAN DEFAULT TRUE,
    effective_date DATETIME,
    expiration_date DATETIME,
    authorization_number VARCHAR(100),
    authorization_date DATETIME,
    notes TEXT,
    status ENUM('ACTIVE', 'INACTIVE', 'EXPIRED', 'PENDING_VERIFICATION') DEFAULT 'ACTIVE',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_patient_id (patient_id),
    INDEX idx_payer_id (payer_id),
    INDEX idx_status (status)
);

-- Code Mappings Table
CREATE TABLE code_mappings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    appointment_type VARCHAR(100) NOT NULL,
    ai_diagnosis VARCHAR(255),
    manual_diagnosis VARCHAR(255),
    cpt_code VARCHAR(10) NOT NULL,
    cpt_description VARCHAR(500),
    icd_10_code VARCHAR(10) NOT NULL,
    icd_10_description VARCHAR(500),
    default_billed_amount DECIMAL(10,2),
    typical_allowed_amount DECIMAL(10,2),
    modifier_1 VARCHAR(2),
    modifier_2 VARCHAR(2),
    modifier_3 VARCHAR(2),
    modifier_4 VARCHAR(2),
    place_of_service VARCHAR(2),
    units INT DEFAULT 1,
    is_active BOOLEAN DEFAULT TRUE,
    priority INT DEFAULT 1,
    notes TEXT,
    created_by VARCHAR(100),
    approved_by VARCHAR(100),
    approval_date DATETIME,
    status ENUM('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'INACTIVE') DEFAULT 'DRAFT',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_appointment_type (appointment_type),
    INDEX idx_cpt_code (cpt_code),
    INDEX idx_icd_10_code (icd_10_code),
    INDEX idx_status (status),
    INDEX idx_priority (priority)
);

-- Insurance Claims Table
CREATE TABLE insurance_claims (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    insurance_info_id BIGINT NOT NULL,
    claim_number VARCHAR(100) UNIQUE,
    control_number VARCHAR(100) UNIQUE,
    claim_date DATETIME NOT NULL,
    service_date DATETIME NOT NULL,
    cpt_code VARCHAR(10) NOT NULL,
    icd_10_code VARCHAR(10) NOT NULL,
    diagnosis_pointer VARCHAR(10),
    billed_amount DECIMAL(10,2) NOT NULL,
    allowed_amount DECIMAL(10,2),
    paid_amount DECIMAL(10,2),
    patient_responsibility DECIMAL(10,2),
    copay_amount DECIMAL(10,2),
    deductible_amount DECIMAL(10,2),
    coinsurance_amount DECIMAL(10,2),
    place_of_service VARCHAR(2),
    modifier_1 VARCHAR(2),
    modifier_2 VARCHAR(2),
    modifier_3 VARCHAR(2),
    modifier_4 VARCHAR(2),
    units INT DEFAULT 1,
    days_supplied INT,
    prescription_number VARCHAR(100),
    refill_number INT,
    prior_authorization VARCHAR(100),
    referring_provider_npi VARCHAR(20),
    rendering_provider_npi VARCHAR(20) NOT NULL,
    billing_provider_npi VARCHAR(20) NOT NULL,
    facility_npi VARCHAR(20),
    edi_file_path VARCHAR(500),
    edi_content TEXT,
    submission_date DATETIME,
    clearinghouse_response TEXT,
    payer_response TEXT,
    response_date DATETIME,
    rejection_reason TEXT,
    appeal_deadline DATETIME,
    notes TEXT,
    status ENUM('DRAFT', 'READY_TO_SUBMIT', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'PAID', 'DENIED', 'APPEALED', 'CLOSED') DEFAULT 'DRAFT',
    submission_status ENUM('NOT_SUBMITTED', 'SUBMITTED_TO_CLEARINGHOUSE', 'ACCEPTED_BY_CLEARINGHOUSE', 'REJECTED_BY_CLEARINGHOUSE', 'SUBMITTED_TO_PAYER', 'ACCEPTED_BY_PAYER', 'REJECTED_BY_PAYER', 'PAID', 'DENIED') DEFAULT 'NOT_SUBMITTED',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (insurance_info_id) REFERENCES insurance_info(id) ON DELETE CASCADE,
    INDEX idx_appointment_id (appointment_id),
    INDEX idx_patient_id (patient_id),
    INDEX idx_doctor_id (doctor_id),
    INDEX idx_claim_number (claim_number),
    INDEX idx_status (status),
    INDEX idx_submission_status (submission_status),
    INDEX idx_service_date (service_date)
);

-- Audit Logs Table
CREATE TABLE audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100) NOT NULL,
    resource_id VARCHAR(100),
    resource_name VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent TEXT,
    session_id VARCHAR(100),
    request_url VARCHAR(500),
    request_method VARCHAR(10),
    request_params TEXT,
    response_status INT,
    response_time_ms BIGINT,
    error_message TEXT,
    ai_usage BOOLEAN DEFAULT FALSE,
    ai_model_used VARCHAR(100),
    ai_input_data TEXT,
    ai_output_data TEXT,
    data_access_level VARCHAR(20),
    compliance_category VARCHAR(50),
    risk_level VARCHAR(20),
    location VARCHAR(255),
    device_info VARCHAR(500),
    notes TEXT,
    severity ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL') DEFAULT 'INFO',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_user_id (user_id),
    INDEX idx_action (action),
    INDEX idx_resource_type (resource_type),
    INDEX idx_created_at (created_at),
    INDEX idx_severity (severity),
    INDEX idx_ai_usage (ai_usage)
);

-- Consents Table
CREATE TABLE consents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    witness_id BIGINT,
    consent_type VARCHAR(100) NOT NULL,
    consent_version VARCHAR(50) NOT NULL,
    consent_title VARCHAR(255),
    consent_content TEXT,
    consent_date DATETIME NOT NULL,
    expiration_date DATETIME,
    revocation_date DATETIME,
    revocation_reason TEXT,
    digital_signature TEXT,
    signature_timestamp DATETIME,
    ip_address VARCHAR(45),
    user_agent TEXT,
    device_info VARCHAR(500),
    location VARCHAR(255),
    language VARCHAR(10) DEFAULT 'en',
    accessibility_mode BOOLEAN DEFAULT FALSE,
    ai_explanation_provided BOOLEAN DEFAULT FALSE,
    ai_risks_explained BOOLEAN DEFAULT FALSE,
    data_usage_explained BOOLEAN DEFAULT FALSE,
    right_to_revoke_explained BOOLEAN DEFAULT FALSE,
    questions_answered BOOLEAN DEFAULT FALSE,
    patient_understood BOOLEAN DEFAULT FALSE,
    witness_present BOOLEAN DEFAULT FALSE,
    notes TEXT,
    status ENUM('DRAFT', 'ACTIVE', 'EXPIRED', 'REVOKED', 'SUPERSEDED') DEFAULT 'ACTIVE',
    compliance_level ENUM('BASIC', 'STANDARD', 'ENHANCED', 'RESEARCH') DEFAULT 'BASIC',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (witness_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_patient_id (patient_id),
    INDEX idx_consent_type (consent_type),
    INDEX idx_status (status),
    INDEX idx_consent_date (consent_date)
);

-- Business Associate Agreements Table
CREATE TABLE baa_agreements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    clinic_name VARCHAR(255) NOT NULL,
    clinic_npi VARCHAR(20),
    contact_name VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20),
    agreement_version VARCHAR(50) NOT NULL,
    agreement_content TEXT,
    effective_date DATETIME NOT NULL,
    expiration_date DATETIME,
    termination_date DATETIME,
    termination_reason TEXT,
    digital_signature TEXT,
    signature_timestamp DATETIME,
    ip_address VARCHAR(45),
    user_agent TEXT,
    status ENUM('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED') DEFAULT 'DRAFT',
    compliance_level ENUM('BASIC', 'STANDARD', 'ENHANCED') DEFAULT 'STANDARD',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_clinic_name (clinic_name),
    INDEX idx_status (status),
    INDEX idx_effective_date (effective_date)
);

-- Insert default code mappings
INSERT INTO code_mappings (appointment_type, cpt_code, cpt_description, icd_10_code, icd_10_description, default_billed_amount, place_of_service, status, created_by) VALUES
('CONSULTATION', '99213', 'Office visit, established patient, 20-29 minutes', 'Z00.00', 'Encounter for general adult medical examination', 150.00, '11', 'APPROVED', 'system'),
('FOLLOW_UP', '99214', 'Office visit, established patient, 30-39 minutes', 'Z51.11', 'Encounter for antineoplastic chemotherapy', 200.00, '11', 'APPROVED', 'system'),
('EMERGENCY', '99284', 'Emergency department visit, moderate complexity', 'R50.9', 'Fever, unspecified', 300.00, '23', 'APPROVED', 'system'),
('TELEMEDICINE', '99444', 'Online evaluation and management service', 'Z00.00', 'Encounter for general adult medical examination', 100.00, '12', 'APPROVED', 'system'),
('AI_CONSULTATION', '99444', 'Online evaluation and management service', 'Z00.00', 'Encounter for general adult medical examination', 120.00, '12', 'APPROVED', 'system');

-- Create indexes for better performance
CREATE INDEX idx_audit_logs_user_action ON audit_logs(user_id, action);
CREATE INDEX idx_audit_logs_resource ON audit_logs(resource_type, resource_id);
CREATE INDEX idx_consents_patient_type ON consents(patient_id, consent_type);
CREATE INDEX idx_claims_appointment_status ON insurance_claims(appointment_id, status);
CREATE INDEX idx_claims_service_date ON insurance_claims(service_date); 