spring:
  application:
    name: ai-telemedicine-platform
  
  datasource:
    url: jdbc:mysql://localhost:3306/telemedicine?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  security:
    user:
      name: admin
      password: admin
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: your-super-secret-jwt-key-that-is-at-least-256-bits-long
    expiration: 3600000 # 1 hour in milliseconds
    refresh-expiration: 86400000 # 24 hours in milliseconds
  
  frontend:
    url: http://localhost:3000
  
  openai:
    api-key: your-openai-api-key
    model: gpt-4
    max-tokens: 1000
  
  stripe:
    secret-key: your-stripe-secret-key
    publishable-key: your-stripe-publishable-key
  
  twilio:
    account-sid: your-twilio-account-sid
    auth-token: your-twilio-auth-token
  
  file:
    upload-dir: ./uploads
    max-size: 10485760 # 10MB

logging:
  level:
    com.aitelemedicine.telemedicine: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 